indexing-settings:
  sites:
    - url: https://www.lutherancathedral.ru
      name: Собор Петра и Павла
    - url: https://www.playback.ru
      name: PlayBack.ru
    - url: https://radiomv.ru
      name: Милицейская Волна
    - url: https://ipfran.ru
      name: ИПФ РАН

search-settings:
  user-agent: "TigerSearchBot"
  referrer: "https://www.google.com"

server:
  port: 8080

spring:
  datasource:
      username: root
      password: girmo$45
      url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update
      show-sql: true
